### ISSUE TITLE
no captive portal

### ISSUE THREAD

**Issue by affleurait4534** [zahichemaly/fake-captive-portal-using-android-phone#2]
It works when visiting an ip like 192.168.1.1, 1.1.1.1
But not when going to google.com.
Also no captive portal pops up when connecting a device.

this is because i'm not using mobile data and can't. Is there anyway to make this work without internet?

**Comment by zahichemaly** [comment]
Sorry for the late reply. Make sure the IP table rules were all inserted correctly. It should work without internet (although I haven't tried ) since any page that you access should redirect you to the portal based on the prerouting rules.
